### PR TITLE
add a 'listen' entrypoint to redirect to an audio only url

### PR DESCRIPTION
**Pull request by eadmaster**
get_result was also changed a bit...

### CODE REVIEW

**Comment by jaimeMF** [comment]
Two things:
* Probably it should use `bestaudio` instead of `m4a`.
* It  can be implemented in a simpler way (in my opinion):
```python
@route_api('listen')
def listen():
    args = dict(request.args)
    args.setdefault('format', 'bestaudio')
    return redirect(url_for('.play', **args))
```

**Comment by eadmaster** [comment]
I've chosen `mp4` because probably it is more compatible with older audio players that may lack opus support.

**Comment by jaimeMF** [comment]
> I've chosen mp4 because probably it is more compatible with older audio players that may lack opus support.

If a player only supports `m4a`, you should specify the `format`.

**Comment by eadmaster** [comment]
Allrighty, i just have to add "&format=m4a" to my urls to get the audio track only...

**Pull request closed without merging**
