### PR TITLE
autostart the app and added top-level entrypoints for url redirections

### PR DESCRIPTION
**Pull request by eadmaster**

### CODE REVIEW

**Comment by jaimeMF** [comment]
Split unrelated changes in different pull requests.

Note that you can already run the server https://github.com/jaimeMF/youtube-dl-api-server/blob/master/youtube_dl_server/__main__.py, so I don't understand why it should be run on mainGAE.py (which is only used for GAE).

**Comment by eadmaster** [comment]
Oh, i see now, sorry. Then I suggest to add a note in the `README.rst` that tells how to start the server:
`python -m youtube_dl_server`

The new entrypoints may also be moved in "/api", if you think it is a good idea (the documentation should be updated after this).

**Comment by jaimeMF** [comment]
> Oh, i see now, sorry. Then I suggest to add a note in the `README.rst` that tells how to start the server:
`python -m youtube_dl_server`

I may do it, but as documented in https://youtube-dl-api-server.readthedocs.io/en/latest/install.html#using-pip, you should install it with pip and just run `youtube-dl-server`.

> The new entrypoints may also be moved in "/api", if you think it is a good idea (the documentation should be updated after this).

I don't know, but please don't duplicate code and move common code to a function.

**Comment by eadmaster** [comment]
Ok, but imo that's an important part that should be included in the main project github page.

Btw i've found that my new endpoints does not work well with playlist and searches urls, so you may consider cancelling this commit:
```
http://localhost/listen?url=youtube.com/results?search_query=zelda+trailer
http://localhost/listen?url=youtube.com/playlist?list=PLhSyQQVdOOFZ0mnX1ZPcY58LDUzIkvlLi
```

**Comment by jaimeMF** [comment]
I have added it as `/api/play` (3f42de2707377bd5cf8a1729d25bb7c695f945e19) and you can now use the `format` parameter (cdffe8afa0853e9643f69caef61527a6db8fe36c), therefore I'm closing it. Thanks for the suggestion!

**Pull request closed without merging**
